version: '2'
services:

  dashboard:
    depends_on:
      - "kibana"
    environment:
      - KIBANA_SRV_PASSWORD=changeme # n.b.: must match the password on elasticsearch
      - ADMINPASSWORD=changeme
    restart: always
    command: ["bash", "/wait-for-it.sh", "kibana:5601", "-t", "0", "--", "/docker-entry.sh"]

  elasticsearch:
    image: inspiremif/elasticsearch:latest
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    environment:
      - NODE_NAME=elasticsearch
      - MINIMUM_MASTER_NODE=2
      - NODE_DATA=true
      - NODE_MASTER=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTICSEARCH_MASTER=YES
      - KIBANA_SRV_PASSWORD=changeme
    restart: always

  elasticsearch-node1:
    image: inspiremif/elasticsearch:latest
    depends_on:
      - "elasticsearch"
    environment:
      - NODE_NAME=elasticsearch-node1
      - MINIMUM_MASTER_NODE=2
      - NODE_DATA=true
      - NODE_MASTER=true
      - DISCOVERY_ZEN="elasticsearch"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTICSEARCH_MASTER=NO
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    restart: always

  elasticsearch-node2:
    image: inspiremif/elasticsearch:latest
    depends_on:
      - "elasticsearch"
    environment:
      - NODE_NAME=elasticsearch-node2
      - MINIMUM_MASTER_NODE=2
      - NODE_DATA=true
      - NODE_MASTER=false
      - DISCOVERY_ZEN="elasticsearch"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTICSEARCH_MASTER=NO
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    restart: always

  cerebro:
    image: inspiremif/cerebro:latest
    depends_on:
      - "elasticsearch"
    environment:
      - SECRET=changeme
    restart: always
    container_name: sandbox-cerebro

  kibana:
    image: inspiremif/kibana:latest
    environment:
      - KIBANA_SRV_PASSWORD=changeme # n.b.: must match the password on elasticsearch
    depends_on:
      - "elasticsearch"
    restart: always
    command: ["bash", "/wait-for-it.sh", "elasticsearch:9200", "-t", "0", "--", "/docker-entry.sh"]

  nginx:
    hostname: nginx
    image: inspiremif/nginx:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/pki/tls/certs/server-eionet.crt:/tmp/cert.crt:ro
      - /etc/pki/tls/private/server-eionet.key:/tmp/priv.key:ro
    depends_on:
      - "dashboard"
    environment:
      - "GENERATESSL=NO"
      - "CERTIFICATESUBJ=/C=DK/ST=Copenhagen/L=Copenhagen/O=EEA/OU=IT Department/CN=inspire-dashboard.eea"
    restart: always
    command: ["sh", "./entry-point.sh"]

  sysctl:
    network_mode: none
    image: rawmind/alpine-sysctl:0.1
    privileged: true
    environment:
      - "SYSCTL_KEY=vm.max_map_count"
      - "SYSCTL_VALUE=262144"
